### ISSUE TITLE
Compatibility with rembg?

### ISSUE THREAD

**Issue by Zarxrax** [CartoonSegmentation/CartoonSegmentation#2]
I'm really excited to see this work, it looks really impressive! I had been trying to work on something similar, but only got as far as building a dataset, but what you've got here is far better than anything I could have done. 
Anyways, as your model seems to be based on ISnet, I was wondering if it would be compatible with rembg or other tools, if the model were converted to onnx? Or have you changed the network structure?

Also, I was curious if you had also considered a matting network for extracting the images from the background? (See Matte-Anything, ViTMatte)

**Comment by SmashinFries** [comment]
I tried converting the model to onnx using [MMDeploy](https://github.com/open-mmlab/mmdetection/tree/main/configs/rtmdet#deploy-rtmdet-instance-segmentation-model) but was unable to produce a working model. Using a [Model Config](https://github.com/open-mmlab/mmdetection/tree/main/configs/rtmdet#model-config) that is specific to the CartoonSegmentation model seems to be needed when converting.
