### ISSUE TITLE
CloudStor Decommission

### ISSUE THREAD

**Issue by Asianfleet** [CartoonSegmentation/CartoonSegmentation#4]
CloudStor has been decommissioned. As of 12pm AEDT on 15 December 2023 we can no longer access CloudStor.Do you have alternative links？

**Comment by ljsabc** [comment]
I think it's related to res101.pth, which can also be found on the file repo of lllyasviel/Annotators on HF.
Alternative file link can be found [here](https://huggingface.co/lllyasviel/Annotators/blob/af19c34529d974eb965a00250f7b743431d56047/res101.pth)

@dmMaze Can we edit this on the codebase directly?

**Comment by dmMaze** [comment]
@Asianfleet @ljsabc Thanks for the reminder. I have replaced the link with the one on HuggingFace.
