### ISSUE TITLE
ImportError: cannot import name 'DualIAATransform' from 'albumentations'

### ISSUE THREAD

**Issue by C00reNUT** [CartoonSegmentation/CartoonSegmentation#5]
Hello, on Ubuntu after installing all depencies using conda and compiling all other prerequisites, when I am running 

`python run_kenburns.py --cfg configs/3dkenburns.yaml --input-img examples/kenburns_lion.png`

`Traceback (most recent call last):
  File "/mnt/a0b764eb-cdc5-4f46-9a2e-e2f11deba631/Video/CartoonSegmentation/run_kenburns.py", line 7, in <module>
    from anime_3dkenburns import KenBurnsPipeline, npyframes2video
  File "/mnt/a0b764eb-cdc5-4f46-9a2e-e2f11deba631/Video/CartoonSegmentation/anime_3dkenburns/__init__.py", line 1, in <module>
    from .kenburns_effect import KenBurnsPipeline, KenBurnsConfig, npyframes2video
  File "/mnt/a0b764eb-cdc5-4f46-9a2e-e2f11deba631/Video/CartoonSegmentation/anime_3dkenburns/kenburns_effect.py", line 20, in <module>
    from animeinsseg.data.syndataset import quantize_image
  File "/mnt/a0b764eb-cdc5-4f46-9a2e-e2f11deba631/Video/CartoonSegmentation/animeinsseg/data/syndataset.py", line 15, in <module>
    from .transforms import get_fg_transforms, get_bg_transforms, quantize_image, resize2height, rotate_image
  File "/mnt/a0b764eb-cdc5-4f46-9a2e-e2f11deba631/Video/CartoonSegmentation/animeinsseg/data/transforms.py", line 2, in <module>
    from albumentations import DualIAATransform, to_tuple
ImportError: cannot import name 'DualIAATransform' from 'albumentations' (/mnt/a0b764eb-cdc5-4f46-9a2e-e2f11deba631/PYTHON_CACHE/CartoonSegmentation/lib/python3.10/site-packages/albumentations/__init__.py)`

albumentations are installed, so I am not sure where is the problem...

**Comment by dmMaze** [comment]
Please install imgaug

**Comment by dmMaze** [comment]
> And if I may one more question - is there and option to disable 'blur' in the generated video - like when it changes focus from foreground to the background or the other way?

You can disable it by setting the following value to False: 
https://github.com/CartoonSegmentation/CartoonSegmentation/blob/b0539d545ef13f2abf40fe3ae6b4652eeef59908/configs/3dkenburns.yaml#L7

**Comment by dmMaze** [comment]
> Just one last thing - would it be possible to control total length of the video, aka speed of the zoom? And possibly to have zooming only in one direction - like zoom in?

Please update your code base, you will be able to control these by modifying the following values now. 
https://github.com/CartoonSegmentation/CartoonSegmentation/blob/749192d5b10c2e3763765b67003e47a1a536c5c0/configs/3dkenburns.yaml#L13-L16

**Comment by dmMaze** [comment]
> Also would it be possible that the zomm in would start from the x=width/2 and y=heigth/2 point aka that the zooming would be always center based? This should minimize the artifacts in case of zoom in, because the depth would cover the background basically reducing amount of inpaining needed.


It will not always result in minimum holes. The autozoom finds the camera which results in minimum missing points for you:
https://github.com/CartoonSegmentation/CartoonSegmentation/blob/749192d5b10c2e3763765b67003e47a1a536c5c0/anime_3dkenburns/common.py#L126-L131


> thank you, I am trying to compare the quality of https://github.com/prs-eth/marigold with your method of depth estimation, would it be possible to insert npy or png depth map directly into the script?

I'll add it to TODO-list
